-- public.cuenta definition

CREATE TABLE public.cuenta (
	estado bool NULL,
	saldo_inicial float8 NULL,
	cuenta_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	identificacion_cliente int8 NOT NULL,
	tipo_cuenta varchar(50) NOT NULL,
	numero_cuenta varchar(75) NOT NULL,
	CONSTRAINT cuenta_pkey PRIMARY KEY (cuenta_id)
);


-- public.movimientos definition

CREATE TABLE public.movimientos (
	valor_transferencia float8 NULL,
	cuenta_id int8 NOT NULL,
	fecha_actualizada timestamp(6) NULL,
	fecha_creacion timestamp(6) NULL,
	fecha_transferencia timestamp(6) NOT NULL,
	movimiento_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cuenta_receptora varchar(50) NOT NULL,
	tipo_cuenta_receptora varchar(50) NOT NULL,
	tipo_movimiento varchar(50) NOT NULL,
	CONSTRAINT movimientos_pkey PRIMARY KEY (movimiento_id)
);




ALTER TABLE public.movimientos ADD CONSTRAINT fk_movimientos_cuenta_id FOREIGN KEY (cuenta_id) REFERENCES public.cuenta(cuenta_id);