version: '3.8'

services:
  bank_postgres:
    image: postgres:16
    container_name: bank_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  bank_client:
    container_name: bank_client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "80:80"
   
  bank_account:
    container_name: bank_account
    build:
      context: .
      dockerfile: account/Dockerfile
    ports:
      - "80:80"   