apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-client
  labels:
    app: bank-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-client
  template:
    metadata:
      labels:
        app: bank-client
    spec:
      containers:
        - name: bank-client
          image: andrews2014/bank-client:latest
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: SWAGGER_ENABLE
              value: "true"
            - name: SPRING_PROFILE
              value: "production"
            - name: JDBC_URL
              value: "jdbc:postgresql://postgres-service:5432/postgres"
            - name: JDBC_DRIVER
              value: "org.postgresql.Driver"
            - name: JDBC_USERNAME
              value: "postgres"
            - name: JDBC_PASSWORD
              value: "postgres"
            - name: HIBERNATE_DDL
              value: "create"
            - name: HIBERNATE_GENERATE
              value: "true"
            - name: HIBERNATE_DIALECT
              value: "org.hibernate.dialect.PostgreSQLDialect"