apiVersion: v1
kind: Service
metadata:
  name: bank-client
  labels:
    app: bank-client
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: bank-client