apiVersion: v1
kind: Service
metadata:
  name: bank-postgres
spec:
  type: ExternalName
  externalName: host.docker.internal
  selector:
    app: bank-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
