
-- Create Client Table public.client
CREATE TABLE public.client (
	status bool NULL,
	client_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	person_id int8 NOT NULL,
	"password" varchar(30) NOT NULL,
	CONSTRAINT client_person_id_key null,
	CONSTRAINT client_pkey PRIMARY KEY (client_id)
);


ALTER TABLE public.client ADD CONSTRAINT "fk_client_join_person" FOREIGN KEY (person_id) REFERENCES public.person(person_id);

-- Create Person Table public.person
CREATE TABLE public.person (
	age int4 NOT NULL,
	person_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	gender varchar(15) NOT NULL,
	national_id varchar(15) NOT NULL,
	telephone varchar(20) NOT NULL,
	"name" varchar(50) NOT NULL,
	address varchar(100) NOT NULL,
	CONSTRAINT person_national_id_key UNIQUE (national_id),
	CONSTRAINT person_pkey PRIMARY KEY (person_id)
);