-- public.persona definition



CREATE TABLE public.persona (
	edad int4 NOT NULL,
	persona_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	identificacion varchar(15) NOT NULL,
	telefono varchar(20) NOT NULL,
	nombre varchar(50) NOT NULL,
	direccion varchar(100) NOT NULL,
	genero varchar(255) NOT NULL,
	CONSTRAINT persona_identificacion_key UNIQUE (identificacion),
	CONSTRAINT persona_pkey PRIMARY KEY (persona_id)
);

-- public.cliente definition

CREATE TABLE public.cliente (
	status bool NULL,
	client_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	persona_id int8 NOT NULL,
	"password" varchar(30) NOT NULL,
	CONSTRAINT cliente_persona_id_key UNIQUE (persona_id),
	CONSTRAINT cliente_pkey PRIMARY KEY (client_id)
);


ALTER TABLE public.cliente ADD CONSTRAINT fk_cliente_persona_id_key FOREIGN KEY (persona_id) REFERENCES public.persona(persona_id);