
-- Delete Client Table
-- DROP TABLE public.cliente;
DROP TABLE public.cliente CASCADE;

-- Delete Person Table
-- DROP TABLE public.persona;
DROP TABLE public.persona ;


-- public.cliente definition

-- Drop table

-- DROP TABLE public.cliente;

CREATE TABLE public.cliente (
	status bool NULL,
	client_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	persona_id int8 NOT NULL,
	"password" varchar(30) NOT NULL,
	CONSTRAINT cliente_persona_id_key UNIQUE (persona_id),
	CONSTRAINT cliente_pkey PRIMARY KEY (client_id)
);


-- public.cliente foreign keys

ALTER TABLE public.cliente ADD CONSTRAINT fk_cliente_persona_id_key FOREIGN KEY (persona_id) REFERENCES public.persona(persona_id);