apiVersion: v1
kind: Service
metadata:
  name: bank-account-movement
  labels:
    app: bank-account-movement
spec:
  type: LoadBalancer
  ports:
    - port: 83
      targetPort: 83
      protocol: TCP
  selector:
    app: bank-account-movement