# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  BuildClient:
    name: Build Client MS and run tests 
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Change wrapper permissions
        working-directory: ./client
        run: |
          chmod +x ./gradlew
          chmod +x gradlew
          chmod +x ./gradle
          chmod +x gradle
            
      - name: Build Client Microservice
        working-directory: ./client
        run: ./gradlew build --no-daemon

      - name: Run unit tests of Client Microservice
        working-directory: ./client
        run: ./gradlew test
        
  BuildAccountAndMovement:
    name: Build Account and Movement MS and run tests 
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Change wrapper permissions
        working-directory: ./account_movement
        run: |
          chmod +x ./gradlew
          chmod +x gradlew
          chmod +x ./gradle
          chmod +x gradle
          
      - name: Build Account and Movement Microservice
        working-directory: ./account_movement
        run: ./gradlew build --no-daemon

      - name: Run unit tests of Account and Movement Microservice
        working-directory: ./account_movement
        run: ./gradlew test    
        
